
if Resource==nil then
	Resource={};
end
Resource[1]={};
Resource[1][1]="English";
Resource[1][2]="Alt Inventory";
Resource[1][3]="by Garan loaded";
Resource[1][4]="Empty";
Resource[1][5]="Capacity";
Resource[1][6]="Full";
Resource[1][7]="Inventory";
Resource[1][8]="Vault";
Resource[1][9]="Shared Storage";
Resource[1][10]="n/a";
Resource[1][11]="Filter";
Resource[1][12]="ALL";
Resource[1][13]="Storage";
Resource[1][14]="Search";
Resource[1][15]="Sort";
Resource[1][16]="Location in bag"; -- sort option 1
Resource[1][17]="Name A-Z"; -- sort option 2
Resource[1][18]="Name Z-A"; -- sort option 3
Resource[1][19]="Category";
Resource[1][20]="Quality"; -- sort option 4
Resource[1][21]="Wear State"; -- sort option 5
Resource[1][22]="Display";
Resource[1][23]="Show All";
Resource[1][24]="General Options";
Resource[1][25]="Inventory View Options";
Resource[1][26]="Timing Delays";
Resource[1][27]="Alt Inventory Options";
Resource[1][28]="Language";
Resource[1][29]="Trim Color";
Resource[1][30]="Back Color";
Resource[1][31]="Text Color";
Resource[1][32]="Default Colors";
Resource[1][33]="Headings Color";
Resource[1][34]="List Text Color";
Resource[1][35]="Panel Back";
Resource[1][36]="Save";
Resource[1][37]="Cancel";
Resource[1][38]="Replace Bags";
Resource[1][39]="Load Minimized";
Resource[1][40]="Show Icon";
Resource[1][41]="Left";
Resource[1][42]="Top";
Resource[1][43]="Display Minimal Header/Footer";
Resource[1][44]="Bag Separator when Sort by \"Location in Bag\"";
Resource[1][45]="Wardrobe";
Resource[1][46]="Are you sure you wish to remove this character's Inventory and Vault information?";
Resource[1][47]="OK";
Resource[1][48]="Options";
Resource[1][49]="Bag";
Resource[1][50]="Insufficient space.";
Resource[1][51]="Drag/Drop only allowed for current character.";
Resource[1][52]="Use mini Icon";
Resource[1][53]="Current bags display total items";
Resource[1][54]="Always load with 'ALL' View"
Resource[1][55]="Item Zoom"
Resource[1][56]="Group Maintenance"
Resource[1][57]="Error"
Resource[1][58]="Error: Group @group not found while deleting."
Resource[1][59]="Confirm Deletion"
Resource[1][60]="Please confirm that you wish to delete group, @group."
Resource[1][61]="OK"
Resource[1][62]="Confirm"
Resource[1][63]="Cancel"
Resource[1][64]="Right click to create New"
Resource[1][65]="New Group"
Resource[1][66]="Add"
Resource[1][67]="Edit Group"
Resource[1][68]="Save"
Resource[1][69]="Delete Group"
Resource[1][70]="<NEW>"
Resource[1][71]="Group"
Resource[1][72]="Name"
Resource[1][73]="Main"
Resource[1][74]="Docked"
Resource[1][75]="Left"
Resource[1][76]="Top"
Resource[1][77]="Width"
Resource[1][78]="Criteria"
Resource[1][79]="Custom Names"
Resource[1][80]="Generic Names"
Resource[1][81]="Categories"
Resource[1][82]="Error: @name already exists in this criteria type for group @group"
Resource[1][83]="@name is not a custom name. Add to 'Custom Names' or 'Generic Names'?"
Resource[1][84]="Confirmation"
Resource[1][85]="Group name, @name, is already in use for this type of inventory."
Resource[1][86]="Saved."
Resource[1][87]="Clear All"
Resource[1][88]="Name is required."
Resource[1][89]="Name already in use."
Resource[1][90]="@category added."
Resource[1][91]="Expanded"
Resource[1][92]="Remove"
Resource[1][93]="Move Top"
Resource[1][94]="Move Up"
Resource[1][95]="Move Down"
Resource[1][96]="Move Bottom"
Resource[1][97]="Moved"
Resource[1][98]="Zoom is temporarily disabled but will be available again in a future release."
Resource[1][99]="Slot"
Resource[1][100]="Character/Slot"
Resource[1][101]="Head" -- equipped item slot types (for allEIPanel)
Resource[1][102]="Chest"
Resource[1][103]="Shoulder"
Resource[1][104]="Hands"
Resource[1][105]="Feet"
Resource[1][106]="Back" -- cape
Resource[1][107]="Legs"
Resource[1][108]="Rings"
Resource[1][109]="Earrings"
Resource[1][110]="Necklace"
Resource[1][111]="Pocket"
Resource[1][112]="Bracelets"
Resource[1][113]="Main Hand"
Resource[1][114]="Off-hand"
Resource[1][115]="Ranged"
Resource[1][116]="Class"
Resource[1][117]="Craft"
Resource[1][118]="ALL (EI)"
Resource[1][119]="Character"
Resource[1][120]="Slot"
Resource[1][121]="Item"
Resource[1][122]="Storage Type"
Resource[1][123]="Use Inventory Groups"
Resource[1][124]="Use Vault Groups"
Resource[1][125]="Copy Groups"
Resource[1][126]="Which group definitions would you like to copy?\nNOTE: This will overwrite any existing group definitions for the @container type."
Resource[1][127]="Dock"
Resource[1][128]="Undock"
Resource[1][129]="Load Default"
Resource[1][130]="Save As Default"
Resource[1][131]="Font"
Resource[1][132]="Crop Delay"
Resource[1][133]="This delay affects how soon after changing displays the zoomed icons that are displayed outside the bounds of a parent control are manually hidden. If when you undock, expand or scroll a set of bags you see icons outside the bounds of the window that persist, try increasing this setting slightly. Note, icons that temporarily flash on screen and disappear are expected. This is a side effect of a glitch in the SetStretchMode API call."
Resource[1][134]="This tab is dedicated to delays that are necessary to account for processing delays in the rendering of stretched images. Note, these only apply when the item zoom is greater than 1. There are a number of factors that can affect stretched images and if any of the expected processes get out of synch it can throw off the entire display. AltInventory is making use of undocumented portions of the API that are not fully implemented and work a bit oddly. Only alter these settings if you begin to see the behaviours mentioned in the descriptions. The measurements are in seconds and should be changed in hundredths (.01) or at most, tenths (.1). Increasing these delays will cause AltInventory to respond slower but may be necessary on some machines."
Resource[1][135]="Max Height"
Resource[1][136]="Remove Character"
Resource[1][137]="Show Current Bags"
Resource[1][138]="Never"
Resource[1][139]="When Minimized"
Resource[1][140]="Always"
Resource[1][141]="Item Explorer"
Resource[1][142]="Min ID"
Resource[1][143]="Max ID"
Resource[1][144]="Durability"
Resource[1][145]="Item Info Detail"
Resource[1][146]="Item ID"
Resource[1][147]="Description"
Resource[1][148]="Max Qty"
Resource[1][149]="Max Stack"
Resource[1][150]="Icon Image"
Resource[1][151]="Background Image"
Resource[1][152]="Quality Image"
Resource[1][153]="Shadow Image"
Resource[1][154]="Underlay Image"
Resource[1][155]="Magic"
Resource[1][156]="Unique"
Resource[1][157]="Client"
Resource[1][158]="Undefined"
-- item durability - Undefined(0) seems to be for non-equipable items (they don't take wear damage so that makes sense)
Resource[1][159]="Flimsy" -- no examples? maybe they all fell into Undefined?  1879216490,1879080101, 1879101876
Resource[1][160]="Weak" -- no examples? maybe they all fell into Undefined? 1879302031
Resource[1][161]="Brittle" -- 7000659b (45)
Resource[1][162]="Normal" -- 70005738 (80?)
Resource[1][164]="Substantial" -- 70017ddc (80)
Resource[1][163]="Tough" -- 7001ff21 (95)
Resource[1][165]="Indestructable" -- doesn't actually ever show in client so 'official' translation doesn't exist
-- item quality - not sure how to get translation strings since the only indicator seems to be color
Resource[1][166]="Common"
Resource[1][167]="Uncommon"
Resource[1][168]="Rare"
Resource[1][169]="Incomparable"
Resource[1][170]="Legendary"
Resource[1][171]="Rescan"

Resource[2]={};
Resource[2][1]="Fran\195\167aise";
Resource[2][2]="Inventaire Autres";
Resource[2][3]=" \195\169crit par Garan charg\195\169";
Resource[2][4]="Vide";
Resource[2][5]="Capacit\195\169";
Resource[2][6]="Plein";
Resource[2][7]="Inventaire";
Resource[2][8]="Coffres";
Resource[2][9]="Stockage Partag\195\169";
Resource[2][10]="n/A";
Resource[2][11]="Filtre";
Resource[2][12]="Tous";
Resource[2][13]="Stockage";
Resource[2][14]="Rech.";
Resource[2][15]="Tri"; -- verified
Resource[2][16]="Ordre dans le Sac"; -- sort option 1
Resource[2][17]="Nom (A-Z)"; -- sort option 2
Resource[2][18]="Nom (Z-A)"; -- sort option 3
Resource[2][19]="Cat\195\169gorie";
Resource[2][20]="Qualit\195\169"; -- sort option 4
Resource[2][21]="\195\137tat D'usure"; -- sort option 5
Resource[2][22]="Afficher";
Resource[2][23]="Tout Afficher"; -- verified
Resource[2][24]="Options Generales";
Resource[2][25]="Options Voir Inventaire";
Resource[2][26]="Retards de synchronisation"
Resource[2][27]="Options Inventaire Autres";
Resource[2][28]="Langue";
Resource[2][29]="Couleur Trim";
Resource[2][30]="Couleur d'arriere";
Resource[2][31]="Couleur du texte";
Resource[2][32]="Couleurs par defaut";
Resource[2][33]="Couleur Rubriques";
Resource[2][34]="Couleur du Texte de la Liste";
Resource[2][35]="fond de panneau"
Resource[2][36]="Enregistrer";
Resource[2][37]="Annuler";
Resource[2][38]="Remplacer Les Sacs";
Resource[2][39]="Charge Minimis\195\169e";
Resource[2][40]="Afficher l'ic\195\180ne lorsqu'elle est r\195\169duite";
Resource[2][41]="Gauche"
Resource[2][42]="Haut"
Resource[2][43]="Affichage Minimum En-t\195\170te/Pied";
Resource[2][44]="S\195\169parateur de Sac Quand Trier par \"Ordre dans le Sac\"";
Resource[2][45]="Wardrobe";
Resource[2][46]="Êtes-vous sûr de vouloir supprimer l'inventaire et les informations du coffre-fort de ce personnage?";
Resource[2][47]="D'accord"
Resource[2][48]="Possibilités"
Resource[2][49]="Sac"
Resource[2][50]="Espace insuffisant."
Resource[2][51]="Glisser/Déposer autorisé uniquement pour le caractère actuel.";
Resource[2][52]="utilisez la mini-icône";
Resource[2][53]="Les sacs actuels affichent le total des articles";
Resource[2][54]="Toujours charger avec la vue « TOUS »"
Resource[2][55]="Zoom pour l'article"
Resource[2][56]="Maintenir des groupes"
Resource[2][57]="Erreur"
Resource[2][58]="Erreur : Groupe, @group, introuvable lors de la suppression."
Resource[2][59]="Confirmer la suppression"
Resource[2][60]="Veuillez confirmer que vous souhaitez supprimer le groupe, @group."
Resource[2][61]="D'accord"
Resource[2][62]="Confirmer"
Resource[2][63]="Annuler"
Resource[2][64]="Faites un clic droit pour créer 'Nouveau'"
Resource[2][65]="Nouveau groupe"
Resource[2][66]="Ajouter"
Resource[2][67]="Modifier le groupe"
Resource[2][68]="Sauvegarder"
Resource[2][69]="Supprimer un groupe"
Resource[2][70]="<Nouveau>"
Resource[2][71]="Groupe"
Resource[2][72]="Nom"
Resource[2][73]="Principal" -- masculine since 'group' is masculine?
Resource[2][74]="Connecté" -- not sure about this one --"Amarré" -- means moored, like a boat, "Accosté" also translates as docked but seems to have the wrong connotation
Resource[2][75]="Gauche"
Resource[2][76]="Haut"
Resource[2][77]="Largeur"
Resource[2][78]="Critères"
Resource[2][79]="Noms personnalisés"
Resource[2][80]="Noms génériques"
Resource[2][81]="Catégories"
Resource[2][82]="Erreur : @name existe déjà dans ce type de critère pour le groupe @group"
Resource[2][83]="@name n'est pas un nom personnalisé. Ajouter aux « Noms personnalisés » ou aux « Noms génériques »?"
Resource[2][84]="Confirmation"
Resource[2][85]="Le nom du groupe, @name, est déjà utilisé pour ce type d'inventaire."
Resource[2][86]="Sauvegardé"
Resource[2][87]="Tout effacer"
Resource[2][88]="Le nom est requis."
Resource[2][89]="Nom déjà utilisé."
Resource[2][90]="@category ajouté."
Resource[2][91]="Élargie" -- réduite ou élargie
Resource[2][92]="Supprimer"
Resource[2][93]="En haut"
Resource[2][94]="Vers le haut"
Resource[2][95]="Vers le bas"
Resource[2][96]="En le bas"
Resource[2][97]="Déplacé"
Resource[2][98]="Zoom est temporairement désactivé mais sera à nouveau disponible dans une prochaine version."
Resource[2][99]="Emplacement"
Resource[2][100]="Personnage/Emplacement"
Resource[2][101]="Tête" -- equipped item slot types (for allEIPanel)
Resource[2][102]="Poitrine"
Resource[2][103]="Épaules"
Resource[2][104]="Gants"
Resource[2][105]="Pieds"
Resource[2][106]="Dos" -- cape
Resource[2][107]="Jambes"
Resource[2][108]="Anneau"
Resource[2][109]="Boucle d'oreille"
Resource[2][110]="Collier"
Resource[2][111]="Poche"
Resource[2][112]="Bracelet"
Resource[2][113]="Arme principale"
Resource[2][114]="Arme secondaire"
Resource[2][115]="Arme à distance"
Resource[2][116]="Objet de class"
Resource[2][117]="Outil d'arisanat"
Resource[2][118]="Tout (EI)"
Resource[2][119]="Personnage"
Resource[2][120]="Emplacement"
Resource[2][121]="Article" -- or Item
Resource[2][122]="Type de stockage"
Resource[2][123]="Utiliser des groupes d'inventaire"
Resource[2][124]="Utiliser des groupes de coffre-fort"
Resource[2][125]="Copier des groupes"
Resource[2][126]="Quelles définitions de groupe souhaitez-vous copier ?\nREMARQUE : cela écrasera toutes les définitions de groupe existantes pour le type @container."
Resource[2][127]="Connecter"
Resource[2][128]="Déconnecter"
Resource[2][129]="Charger les valeurs par défaut"
Resource[2][130]="Enregistrer par défaut"
Resource[2][131]="Police de caractère"
Resource[2][132]="Délai d'recadrer"
Resource[2][133]="Ce délai affecte la durée après laquelle les icônes zoomées affichées en dehors des limites d'un contrôle parent sont masquées manuellement après le changement d'affichage. Si lorsque vous détachez, développez ou faites défiler un ensemble de sacs, vous voyez des icônes persistantes en dehors des limites de la fenêtre, essayez d'augmenter légèrement ce paramètre. Notez que des icônes qui clignotent temporairement à l'écran et disparaissent sont attendues. Il s'agit d'un effet secondaire d'un problème dans l'appel d'API SetStretchMode."
Resource[2][134]="Cet onglet est dédié aux délais nécessaires pour tenir compte des délais de traitement dans le rendu des images étirées. Notez que ceux-ci ne s'appliquent que lorsque le zoom de l'élément est supérieur à 1. Il existe un certain nombre de facteurs qui peuvent affecter les images étirées et si l'un des processus attendus n'est pas synchronisé, cela peut perturber l'ensemble de l'affichage. AltInventory utilise des parties non documentées de l'API qui ne sont pas entièrement implémentées et fonctionnent un peu bizarrement. Ne modifiez ces paramètres que si vous commencez à voir les comportements mentionnés dans les descriptions. Les mesures sont en secondes et doivent être modifiées en centièmes (.01) ou au plus en dixièmes (.1). L'augmentation de ces délais entraînera une réponse plus lente d'AltInventory, mais peut être nécessaire sur certaines machines."
Resource[2][135]="Hauteur maximale"
Resource[2][136]="Supprimer la Personnage"
Resource[2][137]="Afficher les sacs actuels"
Resource[2][138]="Jamais"
Resource[2][139]="Lorsqu'il est minimisé"
Resource[2][140]="Toujours"
Resource[2][141]="Explorateur d'objets"
Resource[2][142]="Min ID"
Resource[2][143]="Max ID"
Resource[2][144]="La durabilité"
Resource[2][145]="Informations détaillées sur l'article"
Resource[2][146]="Identifiant"
Resource[2][147]="​La description"
Resource[2][148]="Max Quantité"
Resource[2][149]="Taille de la pile"
Resource[2][150]="L'image d'icône"
Resource[2][151]="L'image de fond"
Resource[2][152]="L'image de qualité"
Resource[2][153]="L'image d'ombre"
Resource[2][154]="L'image de sous-couche"
Resource[2][155]="Magique"
Resource[2][156]="Unique"
Resource[2][157]="Client"
Resource[2][158]="Indéfinie"

Resource[3]={};
Resource[3][1]="Deutsch";
Resource[3][2]="Alt Inventar";
Resource[3][3]=" von Garan geladen";
Resource[3][4]="Leer"; -- verified
Resource[3][5]="Kapazit\195\164t"; -- 
Resource[3][6]="Voll";
Resource[3][7]="Inventar";
Resource[3][8]="Bank"; -- why not Tresor?
Resource[3][9]="Gemeinsamer Lagerraum"; -- or Gemeinsamer Lagerraum
Resource[3][10]="n/A"
Resource[3][11]="Filter";
Resource[3][12]="ALLES";
Resource[3][13]="Lagerung";
Resource[3][14]="Suchen";
Resource[3][15]="Sort."; --verified
Resource[3][16]="wie Originalbeutel"; -- Correction provided by Schlumpf
Resource[3][17]="Name A-Z"; -- sort option 2
Resource[3][18]="Name Z-A"; -- sort option 3
Resource[3][19]="Kategorie";
Resource[3][20]="Qualit\195\164t"; -- sort option 4
Resource[3][21]="Abnutzung Zustand"; -- sort option 5
Resource[3][22]="Anzeigen";
Resource[3][23]="Alle Anzeigen";--verified
Resource[3][24]="Allgemeine Optionen";
Resource[3][25]="Inventar Ansichtsoptionen";
Resource[3][26]="Zeitverzögerungen"
Resource[3][27]="Alt Inventar Optionen";
Resource[3][28]="Sprache";
Resource[3][29]="Dekorfarbe";
Resource[3][30]="Hintergrundfarbe";
Resource[3][31]="Textfarbe";
Resource[3][32]="Standardfarben"; -- Correction provided by Schlumpf
Resource[3][33]="Farbe \195\156berschrift "; -- Correction provided by Schlumpf
Resource[3][34]="Farbe Listen"; -- Correction provided by Schlumpf
Resource[3][35]="Panel-Hintergrund"
Resource[3][36]="Speichern";
Resource[3][37]="Abbrechen";-- verified
Resource[3][38]="Originalbeutel ersetzen"; -- Correction provided by Schlumpf
Resource[3][39]="minimiert laden"; -- Correction provided by Schlumpf
Resource[3][40]="zum Symbol minimieren"; -- correction provided by Schlumpf
Resource[3][41]="Gauche"
Resource[3][42]="Spitze"
Resource[3][43]="Fenster ohne Dekorrahmen"; -- Correction provided by Schlumpf
Resource[3][44]="getrennte Beutel bei Sortierung \"wie Originalbeutel\""; -- Correction provided by Schlumpf
Resource[3][45]="Schrank"; -- or Kleiderschrank
Resource[3][46]="Sind Sie sicher, dass Sie die Inventar- und Tresor Informationen dieses Charakters löschen möchten?";
Resource[3][47]="OK"
Resource[3][48]="Optionen"
Resource[3][49]="Beutel"
Resource[3][50]="Nicht genug Platz."
Resource[3][51]="Drag/Drop ist nur für den aktuellen Charakter erlaubt."
Resource[3][52]="Verwenden Sie das Mini-Symbol"
Resource[3][53]="Aktuelle Taschen zeigen die Gesamtzahl der Artikel an"
Resource[3][54]="Laden Sie immer mit der Ansicht „ALLES“."
Resource[3][55]="Zoomstufe für Element"
Resource[3][56]="Gruppen pflegen"
Resource[3][57]="Fehler"
Resource[3][58]="Fehler: Gruppe, @group, beim Löschen nicht gefunden."
Resource[3][59]="Löschung bestätigen"
Resource[3][60]="Bitte bestätigen Sie, dass Sie die Gruppe @group löschen möchten."
Resource[3][61]="OK"
Resource[3][62]="Bestätigen"
Resource[3][63]="Abbrechen"
Resource[3][64]="Klicken Sie mit der rechten Maustaste, um „Neue“ zu erstellen."
Resource[3][65]="Neue Gruppe"
Resource[3][66]="Hinzufügen"
Resource[3][67]="Gruppe bearbeiten"
Resource[3][68]="Speichern"
Resource[3][69]="Gruppe löschen"
Resource[3][70]="<Neue>"
Resource[3][71]="Gruppe"
Resource[3][72]="Name"
Resource[3][73]="Haupt" -- really not sure on this one
Resource[3][74]="Angedockt"
Resource[3][75]="Gauche"
Resource[3][76]="Spitze"
Resource[3][77]="Breite"
Resource[3][78]="Kriterien"
Resource[3][79]="Benutzerdefinierte Namen"
Resource[3][80]="Gattungsnamen"
Resource[3][81]="Kategorien"
Resource[3][82]="Fehler: @name ist in diesem Kriterien Typ für die Gruppe @group bereits vorhanden"
Resource[3][83]="@name ist kein benutzerdefinierter Name. Zu „Benutzerdefinierte Namen“ oder „Gattungsnamen“ hinzufügen?"
Resource[3][84]="Bestätigung"
Resource[3][85]="Der Gruppenname @name wird bereits für diese Art von Inventar verwendet."
Resource[3][86]="Gesichert."
Resource[3][87]="Alles löschen"
Resource[3][88]="Name ist erforderlich."
Resource[3][89]="Name bereits verwendet."
Resource[3][90]="@category hinzugefügt."
Resource[3][91]="erweitert" --reduziert oder erweitert
Resource[3][92]="Entfernen"
Resource[3][93]="Spitze"
Resource[3][94]="Nach oben"
Resource[3][95]="Nach unten"
Resource[3][96]="Ganz unten"
Resource[3][97]="Versetzt"
Resource[3][98]="Zoom ist vorübergehend deaktiviert, wird aber in einer zukünftigen Version wieder verfügbar sein."
Resource[3][99]="Steckplatz"
Resource[3][100]="Charakter/Steckplatz"
Resource[3][101]="Kopf" -- equipped item slot types (for allEIPanel)
Resource[3][102]="Brust"
Resource[3][103]="Schultern"
Resource[3][104]="Handschuhe"
Resource[3][105]="Füße"
Resource[3][106]="Rücken" -- cape
Resource[3][107]="Beine"
Resource[3][108]="Ring"
Resource[3][109]="Ohrring"
Resource[3][110]="Halskette"
Resource[3][111]="Taschenplatz"
Resource[3][112]="Armband"
Resource[3][113]="Primärwaffe"
Resource[3][114]="Sekundärwaffe"
Resource[3][115]="Fernwaffen"
Resource[3][116]="Klassenfeld"
Resource[3][117]="Handwerkzeug"
Resource[3][118]="ALLES (EI)"
Resource[3][119]="Charakter"
Resource[3][120]="Steckplatz"
Resource[3][121]="Artikel"
Resource[3][122]="Speichertyp"
Resource[3][123]="Verwenden Sie Inventargruppen"
Resource[3][124]="Verwenden Sie Vault-Gruppen"
Resource[3][125]="Gruppen kopieren"
Resource[3][126]="Welche Gruppendefinitionen möchten Sie kopieren?\nHINWEIS: Dadurch werden alle vorhandenen Gruppendefinitionen für den Typ @container überschrieben."
Resource[3][127]="Docken"
Resource[3][128]="Abdocken"
Resource[3][129]="Standardwerte laden"
Resource[3][130]="Standardwerte speichern"
Resource[3][131]="Schriftart"
Resource[3][132]="Trimmverzögerung"
Resource[3][133]="Diese Verzögerung wirkt sich auf die Zeitspanne aus, nach der vergrößerte Symbole, die außerhalb der Grenzen eines übergeordneten Steuerelements angezeigt werden, nach dem Ansichtswechsel manuell ausgeblendet werden. Wenn Sie beim Trennen, Erweitern oder Scrollen durch ein beutel dauerhafte Symbole außerhalb der Fenstergrenzen sehen, versuchen Sie, diese Einstellung leicht zu erhöhen. Beachten Sie, dass es zu erwarten ist, dass Symbole vorübergehend auf dem Bildschirm blinken und wieder verschwinden. Dies ist ein Nebeneffekt eines Problems im SetStretchMode-API-Aufruf."
Resource[3][134]="Diese Registerkarte ist den Verzögerungen gewidmet, die erforderlich sind, um Verarbeitungszeiten beim Rendern gestreckter Bilder zu berücksichtigen. Beachten Sie, dass diese nur gelten, wenn der Elementzoom größer als 1 ist. Es gibt eine Reihe von Faktoren, die sich auf gestreckte Bilder auswirken können, und wenn einer der erwarteten Prozesse nicht synchron ist, kann dies zu Störungen bei der gesamten Anzeige führen. AltInventory verwendet undokumentierte Teile der API, die nicht vollständig implementiert sind und etwas seltsam funktionieren. Ändern Sie diese Einstellungen nur, wenn Sie die in den Beschreibungen erwähnten Verhaltensweisen bemerken. Die Messungen erfolgen in Sekunden und müssen in Hundertstel (.01) oder höchstens Zehntel (.1) geändert werden. Eine Erhöhung dieser Verzögerungen führt dazu, dass AltInventory langsamer reagiert, kann jedoch auf einigen Computern erforderlich sein."
Resource[3][135]="Maximale Höhe"
Resource[3][136]="Löschen Sie das Zeichen"
Resource[3][137]="Aktuelle Taschen anzeigen"
Resource[3][138]="niemals"
Resource[3][139]="Wenn es minimiert wird"
Resource[3][140]="stets"
Resource[3][141]="Objekt-Explorer"
Resource[3][142]="Min ID"
Resource[3][143]="Max ID"
Resource[3][144]="haltbarkeit"
Resource[3][145]="Detaillierte Informationen zum Artikel"
Resource[3][146]="identität"
Resource[3][147]="​beschreibung"
Resource[3][148]="maximale Menge"
Resource[3][149]="stapelgröße"
Resource[3][150]="icon-bild" -- or symbolbild?
Resource[3][151]="hintergrundbild"
Resource[3][152]="qualitätsbild"
Resource[3][153]="schattenbild"
Resource[3][154]="unterlagebild"
Resource[3][155]="magisch"
Resource[3][156]="einzigartig"
Resource[3][157]="Kunde"
Resource[3][158]="Undefiniert"

-- russian translations courtesy of Chirick86 on lotrointerface.com
Resource[4]={};
Resource[4][1]="Russian";
Resource[4][2]="Alt Inventory";
Resource[4][3]="Загружен.\nПеревод: Чирик";
Resource[4][4]="Пусто";
Resource[4][5]="Вместительность";
Resource[4][6]="Переполнен";
Resource[4][7]="Инвентарь";
Resource[4][8]="Банк";
Resource[4][9]="Общий банк";
Resource[4][10]="N/A";
Resource[4][11]="Фильтр";
Resource[4][12]="Все";
Resource[4][13]="Хранилище";
Resource[4][14]="Поиск";
Resource[4][15]="Сортировка";
Resource[4][16]="Позиция в сумке"; -- sort option 1
Resource[4][17]="От А до Я"; -- sort option 2
Resource[4][18]="От Я до А"; -- sort option 3
Resource[4][19]="Категория";
Resource[4][20]="Количество"; -- sort option 4
Resource[4][21]="Состояние"; -- sort option 5
Resource[4][22]="Отобразить";
Resource[4][23]="Показать все";
Resource[4][24]="Главные настройки";
Resource[4][25]="Настройки вида инвентаря";
Resource[4][26]="Вкладка 3";
Resource[4][27]="Alt Inventory Настройки";
Resource[4][28]="Язык";
Resource[4][29]="Цвет Trim";
Resource[4][30]="Цвет фона";
Resource[4][31]="Цвет текста";
Resource[4][32]="Цвета по умолчанию";
Resource[4][33]="Цвет заголовка";
Resource[4][34]="Цвет текста в списке";
Resource[4][35]="Фон окна";
Resource[4][36]="Сохранить";
Resource[4][37]="Отменить";
Resource[4][38]="Сменить сумки";
Resource[4][39]="Загружать в свернутом виде";
Resource[4][40]="Показать иконку когда свернут";
Resource[4][41]="Лево";
Resource[4][42]="Верх";
Resource[4][43]="Показывать минимальный Заголовок/подвал";
Resource[4][44]="Разделять сумки когда сортирова \"Позиция в сумке\"";
Resource[4][45]="Гардероб";
Resource[4][46]="Ходите удалить информацию об этом персонаже?";
Resource[4][47]="OK";
Resource[4][48]="Настройки";
Resource[4][49]="Сумка";
Resource[4][50]="Недостаточно места.";
Resource[4][51]="Перетягивание работает только для текущего персонажа.";
Resource[4][52]="Использовать мини иконку";
Resource[4][53]="Отображать общее количество предметов выбранной сумки";
Resource[4][54]="Загружать по умолчанию в режиме \"Отображать все\""

Resource[4][401]="клиент"

local tmpIndex;
for tmpIndex=1,#Resource[1] do
	if Resource[2][tmpIndex]==nil then Resource[2][tmpIndex]=Resource[1][tmpIndex] end
	if Resource[3][tmpIndex]==nil then Resource[3][tmpIndex]=Resource[1][tmpIndex] end
end
